myapp/urls.py
from django.urls import path
from . import views

app_name = 'myapp'

urlpatterns = [
    path('', 
         views.IndexView.as_view(), 
         name='index'),

    path('post/', 
         views.CreateCompanyView.as_view(), 
         name='post'),

    path('list/', 
         views.PostView.as_view(), 
         name='list'),

    path('success/',
         views.PostSuccessView.as_view(),
         name = 'success'),

     path('todo/', 
          views.TodoListView.as_view(), 
          name='todo_list'),

    path('todo/toggle/<int:task_id>/', 
         views.toggle_task, 
         name='toggle_task'),

    path('todo/delete/<int:task_id>/', 
         views.delete_task, 
         name='delete_task'),  

    path('detail/<int:pk>',
         views.DetailView.as_view(),
         name = 'detail'),
    
    path('search/', 
         views.CompanyListView.as_view(), 
         name='search'),

     path('contact/',
          views.ContactView.as_view(),
          name='contact')
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('myapp.urls')),

]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

myapp/models.py
from django.db import models

class Company(models.Model):
    name = models.CharField(
        max_length=255,verbose_name='会社名',blank=False,null=False)
    image = models.ImageField(
        upload_to='images/',verbose_name='会社画像',blank=False,null=False,default='images/default.png')
    job_description = models.TextField(
        verbose_name='仕事内容',blank=False,null=False)
    strengths = models.CharField(max_length=255,blank=True,null=True,default="特になし",verbose_name='強み')
    location = models.CharField(max_length=255, blank=False, null=False, default="未定", verbose_name='勤務地')
    working_hours = models.CharField(max_length=255, blank=True, null=True, default="不明", verbose_name='勤務時間')
    salary = models.CharField(max_length=255, blank=True, null=True, default="要相談", verbose_name='給料')
    benefits = models.CharField(max_length=255, blank=True, null=True, default="特になし", verbose_name='福利厚生')
    annual_holidays = models.CharField(max_length=255, blank=True, null=True, default="未定", verbose_name='年間休日')
    hires = models.CharField(max_length=255, blank=True, null=True, default="不明", verbose_name='採用人数')
    selection_process = models.TextField(blank=True, null=True, default="選考フローは未定", verbose_name='選考フロー')
    notes = models.TextField(blank=True, null=True, default="特記事項なし", verbose_name='備考')

    def __str__(self):
        return self.name


class Task(models.Model):
    title = models.CharField(max_length=255)
    is_completed = models.BooleanField(default=False)

    def __str__(self):
        return self.title

myapp/forms.py
from django.forms import ModelForm
from .models import Company,Task
from django import forms
from django.core.mail import send_mail
from django.core.mail import BadHeaderError

class CompanyForm(ModelForm):

    class Meta:

        model = Company
        fields = ['name', 'image', 'job_description', 'strengths', 'location', 'working_hours', 'salary', 'benefits', 'annual_holidays', 'hires', 'selection_process', 'notes'] 


class TaskForm(ModelForm):

    class Meta:

        model = Task
        fields = ['title']



class ContactForm(forms.Form):
    name = forms.CharField(label='お名前')
    email = forms.CharField(label='メールアドレス')
    title = forms.CharField(label='件名')
    message = forms.CharField(label='メッセージ')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['placeholder'] = \
        'お名前を入力してください'
        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = \
        'メールアドレスを入力してください'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['title'].widget.attrs['placeholder'] = \
        'タイトルを入力してください'
        self.fields['title'].widget.attrs['class'] = 'form-control'
        self.fields['message'].widget.attrs['placeholder'] = \
        'メッセージを入力してください'
        self.fields['message'].widget.attrs['class'] = 'form-control'

myapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.base import TemplateView
from django.views.generic import CreateView, ListView, DetailView, FormView
from django.urls import reverse_lazy
from .forms import CompanyForm
from .models import Task
from .forms import TaskForm, ContactForm
from django.utils.decorators import method_decorator
from .models import Company
from django.contrib import messages
from django.core.mail import EmailMessage
from django.views.generic.edit import FormMixin
from django.db.models import Q

class IndexView(ListView):
    template_name = 'index.html'
    queryset = Company.objects.order_by('-name')
    paginate_by = 8

class PostView(ListView):
    template_name = "list.html"
    queryset = Company.objects.order_by('-name')

class CreateCompanyView(CreateView):
    form_class = CompanyForm
    template_name = "post.html"
    success_url = reverse_lazy('myapp:success')

    def form_valid(self, form):
        postdate = form.save(commit=False)
        postdate.user = self.request.user

        if not postdate.strengths:
            postdate.strengths = "特になし"
        if not postdate.location:
            postdate.location = "未定"
        if not postdate.working_hours:
            postdate.working_hours = "不明"
        if not postdate.salary:
            postdate.salary = "要相談"
        if not postdate.benefits:
            postdate.benefits = "特になし"
        if not postdate.annual_holidays:
            postdate.annual_holidays = "未定"
        if not postdate.hires:
            postdate.hires = "不明"
        if not postdate.selection_process:
            postdate.selection_process = "選考フローは未定"
        if not postdate.notes:
            postdate.notes = "特記事項なし"

        postdate.save()
        return super().form_valid(form)
    
class PostSuccessView(TemplateView):
    template_name = 'success.html'

class TodoListView(FormMixin, ListView):
    model = Task
    template_name = 'todo.html'
    context_object_name = 'tasks'
    form_class = TaskForm

    def get_queryset(self):
        return Task.objects.all().order_by('-id')

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            form.save()
            return redirect('myapp:todo_list')
        return self.form_invalid(form)


def toggle_task(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    task.is_completed = not task.is_completed
    task.save()
    return redirect('myapp:todo_list')

def delete_task(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    task.delete()
    return redirect('myapp:todo_list')

class DetailView(DetailView):
    model = Company
    template_name = 'detail.html'


class CompanyListView(ListView):
    model = Company
    template_name = 'search.html'
    context_object_name = 'companies'

    def get_queryset(self):
        query = self.request.GET.get('query', '').strip()
        sort = self.request.GET.get('sort', '').strip()

        queryset = Company.objects.all()

        if query:
            queryset = queryset.filter(
                Q(name__icontains=query)  
            )

        valid_sort_fields = ['name', '-name', 'created_at', '-created_at']  
        if sort in valid_sort_fields:
            queryset = queryset.order_by(sort)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('query', '').strip()
        context['sort'] = self.request.GET.get('sort', '').strip()
        return context


class ContactView(FormView):

    template_name ='contact.html'
    form_class = ContactForm
    success_url = reverse_lazy('myapp:contact')

    def form_valid(self, form):
    
        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        title = form.cleaned_data['title']
        message = form.cleaned_data['message']
        subject = 'お問い合わせ: {}'.format(title)
        
        message = \
          '送信者名: {0}\nメールアドレス: {1}\n タイトル:{2}\n メッセージ:\n{3}' \
          .format(name, email, title, message)
        from_email = 'ngn2449954@stu.o-hara.ac.jp'
        to_list = ['ngn2449954@stu.o-hara.ac.jp']
        message = EmailMessage(subject=subject,
                               body=message,
                               from_email=from_email,
                               to=to_list,
                               )
        message.send()
        messages.success(
          self.request, 'お問い合わせは正常に送信されました。')
        return super().form_valid(form)

myapp/templates/index.html
{% load static %}

<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}" />
    <title>{% block title %}集職活動{% endblock %}</title>

  
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="{% static 'css/styles212.css' %}" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@400..900&family=Zen+Kurenaido&display=swap" rel="stylesheet">  

  </head>
  <body>
    
<header>
    <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top" >
        <div class="container" >
              </a>
            <a class="navbar-brand" href="{% url 'myapp:index' %}" style="font-size:24px; font-family: 'Zen Kurenaido', sans-serif;">集職活動</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" style="font-size:18px; font-family: 'Zen Kurenaido', sans-serif;" href="{% url 'myapp:post' %}">企業登録</a>
                        <li class="nav-item">
                            <a class="nav-link" style="font-size:18px; font-family: 'Zen Kurenaido', sans-serif;" href="{% url 'myapp:search' %}">検索</a>    
                    <li class="nav-item">
                        <a class="nav-link" style="font-size:18px; font-family: 'Zen Kurenaido', sans-serif;" href="{% url 'myapp:todo_list' %}">ToDo</a>

                </ul>
            </div>
        </div>
    </nav>
</header>

<main>
    {% include "title.html" %}

</main>

    {% include "list.html" %}

    
    {% include "pagination.html" %}


  </body>

  <footer class="text-muted py-5 custom-dark-bg2">
    <div class="container">
        <p class="mb-1 d-flex align-items-center justify-content-between">
            <span>© 2024 集職活動 | 就職活動のための企業情報収集サイト | 
            <span class="contact-link"><a href="{% url 'myapp:contact' %}">Contact</a></span>
        </p>
    </div>
</footer>


  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" 
  integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
</html>

templates/contact.html
    {% load static %}

<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}" />
    <title>{% block title %}Contact{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="{% static 'css/styles212.css' %}" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dela+Gothic+One&family=Zen+Kurenaido&display=swap" rel="stylesheet">   
  </head>
  <body>
    <div class="jumbotron-extend5">    
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark navbar-custom" >
            <div class="container">
                  </a>
                <a class="navbar-brand" href="{% url 'myapp:index' %}" style="font-size:24px; font-family: 'Zen Kurenaido', sans-serif;">集職活動</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link" style="font-size:18px; font-family: 'Zen Kurenaido', sans-serif;" href="{% url 'myapp:post' %}">企業登録</a>
                            <li class="nav-item">
                                <a class="nav-link" style="font-size:18px; font-family: 'Zen Kurenaido', sans-serif;" href="{% url 'myapp:search' %}">検索</a>    
                        <li class="nav-item">
                            <a class="nav-link" style="font-size:18px; font-family: 'Zen Kurenaido', sans-serif;" href="{% url 'myapp:todo_list' %}">ToDo</a>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    
        <!-- Main Content-->
        {% block contents %}
        <main>
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="container text-center">
                            <h2 class="mb-4 white4">Contact Me</h2>
                          </div>
                        {% if messages %}
                        <ul class="list-unstyled" style="list-styles: none;">
                            {% for message in messages %}
                            <li {% if message.tags %} class="{{message.tags}}" {% endif%}>
                                {{ message }}
                            </li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                                
                        <div class="my-2">
                            <form method="post">
                                {% csrf_token %}
                                {% for field in form %}
                                    <div class="form-floating">
                                        <div class="form-group floating-label-form-group controls white3">
                                            {{ field.label_tag }}
                                            {{ field }}
                                            <p class="help-block text-danger"></p>
                                        </div>
                                    </div>
                                {% endfor %}
                                <br>
                                <div class="button-container">
                                    <button type="submit" class="submit-button"  id="sendMessageButton" >送る</button>
                                </div>                
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            <hr>
        </main>
        {% endblock %}

    </body>
</html>

templates/detail.html
{% load static %}

<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}" />
    <title>{% block title %}{{ object.name }}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="{% static 'css/styles212.css' %}" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dela+Gothic+One&family=Zen+Kurenaido&display=swap" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
        
      }


    </style>

    
  </head>
  <div class="jumbotron-extend3">   
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark navbar-custom" >
            <div class="container">
                  </a>
                <a class="navbar-brand" href="{% url 'myapp:index' %}" style="font-size:24px; font-family: 'Zen Kurenaido', sans-serif;">集職活動</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link" style="font-size:18px; font-family: 'Zen Kurenaido', sans-serif;" href="{% url 'myapp:post' %}">企業登録</a>
                            <li class="nav-item">
                                <a class="nav-link" style="font-size:18px; font-family: 'Zen Kurenaido', sans-serif;" href="{% url 'myapp:search' %}">検索</a>    
                        <li class="nav-item">
                            <a class="nav-link" style="font-size:18px; font-family: 'Zen Kurenaido', sans-serif;" href="{% url 'myapp:todo_list' %}">ToDo</a>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

{% block contents %}
<body class="detail-page">
    <div class="container  h-100">
                            <div class="row d-flex justify-content-center align-items-center h-100">
                            <div class="col-md-10 col-lg-10 ">
                                <div class="card mb-5">
                                    <div class="card-body p-3 ">
                                <div class="col2">
                                    <h1>{{ object.name }}</h1>
                                    <img src="{{ object.image.url }}" height="500"></img>
                                    <h2>仕事内容</h2>
                                        <p>{{ object.job_description }}</p>
                                    {% comment %} <h2>会社の強み</h2>
                                    <p>{{ object.strengths }}</p> {% endcomment %}
                                    <h2>勤務地</h2>
                                    <p>{{ object.location  }}</p>
                                    <h2>勤務時間</h2>
                                    <p>{{ object.working_hours }}</p>
                                    <h2>給料</h2>
                                    <p>{{ object.salary }}</p>
                                    <h2>福利厚生</h2>
                                    <p>{{ object.benefits }}</p>
                                    <h2>年間休日</h2>
                                    <p>{{ object.annual_holidays }}</p>
                                    <h2>採用人数</h2>
                                    <p>{{ object.hires }}</p>
                                    <h2>選考フロー</h2>
                                    <p>{{ object.selection_process }}</p>
                                    <h2>備考</h2>
                                    <p>{{ object.notes }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</div>
{% endblock %}

templates/success.html
{% load static %}

<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}" />
    <title>{% block title %}登録完了{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="{% static 'css/styles212.css' %}" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dela+Gothic+One&family=Zen+Kurenaido&display=swap" rel="stylesheet">

    
  </head>
  <body>
<div class="jumbotron-extend4">    
<header>
    <nav class="navbar navbar-expand-lg navbar-dark navbar-custom" >
        <div class="container">
              </a>
            <a class="navbar-brand" href="{% url 'myapp:index' %}" style="font-size:24px; font-family: 'Zen Kurenaido', sans-serif;">集職活動</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" style="font-size:18px; font-family: 'Zen Kurenaido', sans-serif;" href="{% url 'myapp:post' %}">企業登録</a>
                        <li class="nav-item">
                            <a class="nav-link" style="font-size:18px; font-family: 'Zen Kurenaido', sans-serif;" href="{% url 'myapp:search' %}">検索</a>    
                    <li class="nav-item">
                        <a class="nav-link" style="font-size:18px; font-family: 'Zen Kurenaido', sans-serif;" href="{% url 'myapp:todo_list' %}">ToDo</a>
                </ul>
            </div>
        </div>
    </nav>
</header>

    {% block contents %}

    <br><br>
    <div class="container">
        <div class="row">
            <div class="col offset-2 white3">
                <h4>投稿が完了しました！</h4>
                <a href="{% url 'myapp:index' %}">return to top</a>
            </div>
        </div>
    </div>
    {% endblock %}
</div>

templates/todo.html
{% load static %}

<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}" />
    <title>{% block title %}ToDo{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="{% static 'css/styles212.css' %}" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dela+Gothic+One&family=Zen+Kurenaido&display=swap" rel="stylesheet">   
  </head>
  <body>
<div class="jumbotron-extend2">    
<header>
    <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top" >
        <div class="container">
              </a>
            <a class="navbar-brand" href="{% url 'myapp:index' %}" style="font-size:24px; font-family: 'Zen Kurenaido', sans-serif;">集職活動</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" style="font-size:18px; font-family: 'Zen Kurenaido', sans-serif;" href="{% url 'myapp:post' %}">企業登録</a>
                        <li class="nav-item">
                            <a class="nav-link" style="font-size:18px; font-family: 'Zen Kurenaido', sans-serif;" href="{% url 'myapp:search' %}">検索</a>    
                    <li class="nav-item">
                        <a class="nav-link" style="font-size:18px; font-family: 'Zen Kurenaido', sans-serif;" href="{% url 'myapp:todo_list' %}">ToDo</a>
                </ul>
            </div>
        </div>
    </nav>
</header>

<section>


    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col col-xl-10">
          <div class="container text-center">
            <h2 class="mb-4 white4">ToDoタスク</h2>
          </div>
          <div class="card">
            <div class="card-body p-5">
              <form method="POST" class="d-flex justify-content-center align-items-center mb-4">
                {% csrf_token %}
                {{ form.title }}
                <button type="submit" style="font-family: 'Zen Kurenaido', sans-serif;" class="btn btn-outline-dark ms-2">追加</button>
              </form>
  
              <ul class="list-group mb-0">
                {% for task in tasks %}
                <li class="list-group-item d-flex align-items-center border-0 mb-2 rounded" style="background-color: #f4f6f7;">
                    <input class="form-check-input me-2" type="checkbox" onchange="location.href='{% url 'myapp:toggle_task' task.id %}'" {% if task.is_completed %}checked{% endif %} />
                    {% if task.is_completed %}
                    <s><span style="font-family: 'Zen Kurenaido', sans-serif;">{{ task.title }}</span></s>
                    {% else %}
                    <span style="font-family: 'Zen Kurenaido', sans-serif;">{{ task.title }}</span>
                    {% endif %}
                    <button class="btn btn btn-outline-danger btn-sm ms-auto" style="font-family: 'Zen Kurenaido', sans-serif;" onclick="location.href='{% url 'myapp:delete_task' task.id %}'">Delete</button>
                  </li>
                  
                {% endfor %}
              </ul>
            </div>
          </div>
  
        </div>
      </div>
    </div>

  </section>
</div>